repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        exclude: ^migrations/
        args: [--strict]
