repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.1
    hooks:
      - id: isort
        exclude: ^.*\b(migrations)\b.*$
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^.*\b(migrations|settings)\b.*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer
