version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    container_name: virtumall-proxy
    depends_on:
      - virtumall_api

  virtumall_api:
    image: aohus/virtu-mall:latest
    ports:
      - 8000:8000
    container_name: virtumall
