version: '3.7'
services:
  api:
    image: aohus/virtu-mall:latest
    deploy:  
      replicas: 4
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        max_attempts: 2
    environment:
      SERVICE_PORTS: 8000
    networks:
      - virtunet

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    networks: 
      - virtunet
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

networks: 
  virtunet: 
    external: true
