# Generated by Django 4.2.7 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True, verbose_name="details"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-name"], name="product_name_6ca798_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="product_created_dcab23_idx"
            ),
        ),
    ]
