# Generated by Django 4.2.7 on 2024-08-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="amount",
            new_name="balance",
        ),
    ]
