# Generated by Django 4.2.7 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["-created_at"], name="order_created_25c9da_idx"),
        ),
    ]
